Repository sonic-net/sonic-snmpagent, pull requests merged in 2020-07, with the labels that each got.

#140 [Namespace]: Fix SNMP AgentX socket connection timeout when using Namespace.get_all()
  src/sonic_ax_impl/mibs/__init__.py
  tests/test_mibs.py
Labels: Request for 201911 Branch

#142 Fix LGTM reported alert of PR#141
  src/sonic_ax_impl/mibs/__init__.py
Labels: Request for 201911 Branch

#146 Update transceiver info DB key names
  src/sonic_ax_impl/mibs/ietf/rfc2737.py
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
Labels: Enhancement, Request for 201911 Branch

#152 [psutil] pin psutil version to 5.7.0
  setup.py
Labels: Bug, Included in 201811 Branch
