Repository sonic-net/sonic-snmpagent, pull requests merged in 2024-01, with the labels that each got.

#303 Fix SNMP dropping some of the queue counter when create_only_config_d…
  src/sonic_ax_impl/mibs/__init__.py
  src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py
  tests/mock_tables/asic0/appl_db.json
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/appl_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/asic2/appl_db.json
  tests/mock_tables/asic2/counters_db.json
  tests/mock_tables/asic2/state_db.json
  tests/mock_tables/counters_db.json
  tests/mock_tables/state_db.json
  tests/namespace/test_queues_stat.py
  tests/test_queues_stat.py
Labels: Request for 202205 Branch, Request for 202305 Branch, Request for 202311 Branch

#304 [action] [PR:303] Fix SNMP dropping some of the queue counter when create_only_config_db_buffers is set to true (#303)
  src/sonic_ax_impl/mibs/__init__.py
  src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py
  tests/mock_tables/asic0/appl_db.json
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/appl_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/asic2/appl_db.json
  tests/mock_tables/asic2/counters_db.json
  tests/mock_tables/asic2/state_db.json
  tests/mock_tables/counters_db.json
  tests/mock_tables/state_db.json
  tests/namespace/test_queues_stat.py
  tests/test_queues_stat.py
Labels: automerge

#305 [action] [PR:303] Fix SNMP dropping some of the queue counter when create_only_config_db_buffers is set to true (#303)
  src/sonic_ax_impl/mibs/__init__.py
  src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py
  tests/mock_tables/asic0/appl_db.json
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/appl_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/asic2/appl_db.json
  tests/mock_tables/asic2/counters_db.json
  tests/mock_tables/asic2/state_db.json
  tests/mock_tables/counters_db.json
  tests/mock_tables/state_db.json
  tests/namespace/test_queues_stat.py
  tests/test_queues_stat.py
Labels: automerge

#306 Set the execute bit on sysDescr_pass.py
  src/sonic_ax_impl/bin/sysDescr_pass.py
Labels: Request for 202305 Branch

#307 [action] [PR:306] Set the execute bit on sysDescr_pass.py (#306)
  src/sonic_ax_impl/bin/sysDescr_pass.py
Labels: automerge

#309 [action] [PR:303] Fix SNMP dropping some of the queue counter when create_only_config_db_buffers is set to true (#303)
  src/sonic_ax_impl/mibs/__init__.py
  src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py
  tests/mock_tables/asic0/appl_db.json
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/appl_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/asic2/appl_db.json
  tests/mock_tables/asic2/counters_db.json
  tests/mock_tables/asic2/state_db.json
  tests/mock_tables/counters_db.json
  tests/mock_tables/state_db.json
  tests/namespace/test_queues_stat.py
  tests/test_queues_stat.py
Labels: automerge

#310 [action] [PR:303] Fix SNMP dropping some of the queue counter when create_only_config_db_buffers is set to true (#303)
  src/sonic_ax_impl/mibs/__init__.py
  src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py
  tests/mock_tables/asic0/appl_db.json
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/appl_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/asic2/appl_db.json
  tests/mock_tables/asic2/counters_db.json
  tests/mock_tables/asic2/state_db.json
  tests/mock_tables/counters_db.json
  tests/mock_tables/state_db.json
  tests/namespace/test_queues_stat.py
  tests/test_queues_stat.py
Labels: automerge
